DROP DATABASE IF EXISTS Genshin; 
CREATE DATABASE Genshin CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;
USE Genshin;

CREATE TABLE `personagemlore` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `subtitle` varchar(255) NOT NULL,
  `description` varchar(500) NOT NULL,
  `avatar` varchar(255) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO `personagemlore` VALUES 
(1,'Albedo','Personagem','Principe do Giz','Albedo é um personagem Geo jogável em Genshin Impact . Humano sintético feito pelo alquimista Rhinedottir , o misterioso Albedo é o Alquimista Chefe e Capitão da Equipe de Investigação dos Cavaleiros de Favonius , por recomendação da aventureira Alice . Com Sacarose como seu assistente, ele tem um desejo infinito de aprender sobre o mundo de Teyvat, estudando cuidadosamente cada objeto ao seu redor.','albedo.png', 'https://static.wikia.nocookie.net/gensin-impact/images/0/00/Character_Albedo_Thumb.png/revision/latest?cb=20210213163457'),
(2,'Kamisato Ayaka','Personagem','Garça da Geada','Kamisato Ayaka (japonês: 神里綾華) é uma personagem jogável Cryo em Genshin Impact. Ela foi jogável durante o primeiro Closed Beta Test em Julho de 2019.','ayaka.png', 'https://static.wikia.nocookie.net/genshin-impact/images/f/fd/Character_Kamisato_Ayaka_Thumb.png/revision/latest?cb=20210812051527&path-prefix=id'),
(3,'Diluc','Personagem','Herdeiro do Adega do Alvorecer', 'Diluc Ragnvindr é um personagem Pyro jogável em Genshin Impact .Nascido no afluente Ragnvindr Clan , Diluc é o atual proprietário da Dawn Winery e um nobre de alta estima em Mondstadt . Enquanto um incidente passado o fez se separar dos Cavaleiros de Favonius , ele continua a proteger Mondstadt à sua maneira.','diluc.png', 'https://static.wikia.nocookie.net/gensin-impact/images/0/02/Character_Diluc_Thumb.png/revision/latest?cb%3D20210213163824'),
(4,'Eula','Personagem','Dança da Onda Cintilante','Eula Lawrence é um personagem Cryo jogável em Genshin Impact .Embora descendente do infame e tirânico Clã Lawrence , Eula cortou seus laços com o clã e se tornou a capitã da Companhia de Reconhecimento com os Cavaleiros de Favonius.','eula.png', 'https://static.wikia.nocookie.net/gensin-impact/images/d/d3/Character_Eula_Thumb.png/revision/latest?cb%3D20210511040616'),
(5,'Ganyu','Personagem','Defensora Devota','Ganyu ( chinês :甘雨 Gānyǔ ) é um personagem Cryo jogável em Genshin Impact .Ela é uma Adeptus meio-qilin sob contrato com o Geo Archon Morax e serve como secretária geral do Liyue Qixing .','ganyu.png', 'https://static.wikia.nocookie.net/gensin-impact/images/0/0a/Character_Ganyu_Thumb.png/revision/latest?cb%3D20210213162851'),
(6,'Hutao','Personagem','Fragrância de Ameixa Descongelada','Hu Tao ( chinês :胡桃 Hú Táo ) é um personagem Pyro jogável em Genshin Impact . As travessuras e excentricidade de Hu Tao desmentem seu papel como a 77ª Diretora da Funerária Wangsheng e seu talento como poeta. No entanto, ela trata as operações do salão com a maior importância e realiza cerimônias fúnebres com a mais alta dignidade e solenidade.','hutao.png',  'https://static.wikia.nocookie.net/gensin-impact/images/a/a4/Character_Hu_Tao_Thumb.png/revision/latest?cb%3D20210228210611'),
(7,'Jean','Personagem','Cavaleira de Dandelion','Jean Gunnhildr é um personagem jogável de Anemo em Genshin Impact . A irmã mais velha de Barbara , e descendente do prestigioso clã Gunnhildr , Jean é o Grão-Mestre Interino dos Cavaleiros de Favonius . Ela está sempre ocupada lidando com a agitação em Mondstadt e trabalhando incansavelmente para manter a Cidade da Liberdade.','jean.png',  'https://static.wikia.nocookie.net/gensin-impact/images/8/89/Character_Jean_Thumb.png/revision/latest?cb%3D20220602180528'),
(8,'Keqing','Personagem','Trovão Condutor','Keqing ( chinês :刻晴 Kèqíng ) é um personagem Electro jogável em Genshin Impact .Como a Yuheng do Liyue Qixing , ela é alguém que busca suas próprias respostas em vez de deixar o caos correr solto em Liyue . Ela escolhe seu próprio caminho com seu próprio poder e habilidade, em vez de deixar os deuses determinarem seu destino.','keqing.png', 'https://static.wikia.nocookie.net/gensin-impact/images/0/06/Character_Keqing_Thumb.png/revision/latest?cb%3D20210213162751'),
(9,'Klee','Personagem','Sol Fugitivo', 'Klee é um personagem Pyro jogável em Genshin Impact .A filha da aventureira intrépida e muitas vezes bastante destrutiva Alice , Klee puxa sua mãe de várias maneiras, para desgosto dos Cavaleiros de Favonius a quem ela foi confiada.','klee.png',  'https://static.wikia.nocookie.net/gensin-impact/images/c/c3/Character_Klee_Thumb.png/revision/latest?cb%3D20210214011911'),
(10,'Mona','Personagem','Reflexão Astral','A astróloga Mona Megistus , alternativamente Mona Megistus, a Astróloga , é uma personagem Hydro jogável em Genshin Impact . Uma astróloga de habilidade e alto orgulho, Mona se estabeleceu em Mondstadt para evitar sofrer a ira de seu mestre depois de ler involuntariamente o diário deste último.','mona.png',  'https://static.wikia.nocookie.net/gensin-impact/images/a/a0/Character_Mona_Thumb.png/revision/latest?cb%3D20220601033558'),
(11,'Qiqi','Personagem','Ressurreição Gélida','Qiqi ( chinês :七七 Qīqī ) é um personagem Cryo jogável em Genshin Impact . Ressuscitada como um zumbi pelos adeptos , ela acabou sob os cuidados de Baizhu e agora trabalha na Farmácia Bubu em Liyue Harbor .','qiqi.png',  'https://static.wikia.nocookie.net/gensin-impact/images/d/d5/Character_Qiqi_Thumb.png/revision/latest?cb%3D20220316020612'),
(12,'Tartaglia','Personagem','Childe', 'Tartaglia , também conhecido como seu codinome " Childe ", é um personagem jogável da Hydro em Genshin Impact . Ele é o décimo primeiro dos Onze Precursores Fatui . Seguindo o perigo aonde quer que vá, Childe está sempre ansioso por um desafio, tornando-o extremamente perigoso, apesar de ser o membro mais jovem.','tartaglia.png',   'https://static.wikia.nocookie.net/gensin-impact/images/5/53/Character_Tartaglia_Thumb.png/revision/latest?cb%3D20210213163935'),
(13,'Venti','Personagem','Cantor dos Ventos Celestiais', 'Venti é um personagem jogável de Anemo em Genshin Impact . Ele é um bardo de espírito livre e amante do vinho em Mondstadt e o atual navio mortal de Barbatos , o Anemo Archon .','venti.png',  'https://static.wikia.nocookie.net/gensin-impact/images/8/8d/Character_Venti_Thumb.png/revision/latest?cb%3D20210214011949'),
(14,'Xiao','Personagem','Guardião Yaksha', 'Xiao ( chinês :魈 Xiāo ) é um personagem jogável de Anemo em Genshin Impact . Ele é um adepto , sob o nome de Alatus , e o único membro sobrevivente dos cinco principais Yakshas despachados por Morax para subjugar os espíritos demoníacos que atormentavam Liyue . Ele atualmente reside em Wangshu Inn e principalmente se restringe a grandes multidões e interações sociais.','xiao.png',  'https://static.wikia.nocookie.net/gensin-impact/images/b/b9/Character_Xiao_Thumb.png/revision/latest?cb%3D20210214012045'),
(15,'Yoimiya','Personagem','Chamas Brincando', 'Naganohara Yoimiya [Nota 1] ( japonês :長野原宵宮 Naganohara Yoimiya ) é um personagem Pyro jogável em Genshin Impact . Yoimiya é o atual proprietário da Naganohara Fireworks ; com seus fogos de artifício coloridos e personalidade extrovertida, Yoimiya é amada por todos na Ilha Narukami . Ela foi cunhada como a "Rainha do Festival de Verão", pois eles acreditam que o verão não é o mesmo sem ela.','yoimiya.png',  'https://static.wikia.nocookie.net/gensin-impact/images/0/05/Character_Yoimiya_Thumb.png/revision/latest?cb%3D20220214235604'),
(16,'Zhongli','Personagem','Andarilho do Reino Mortal','Zhongli ( chinês :钟离 Zhōnglí ) é um personagem Geo jogável em Genshin Impact . Um consultor do Wangsheng Funeral Parlor , ele mais tarde é revelado como o atual navio do Geo Archon , Morax , que decidiu experimentar o mundo da perspectiva de um mortal.','zhongli.png',  'https://static.wikia.nocookie.net/gensin-impact/images/c/c2/Character_Zhongli_Thumb.png/revision/latest?cb%3D20210213163026');

CREATE TABLE `personagem` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `subtitle` varchar(255) NOT NULL,
  `description` varchar(500) NOT NULL,
  `avatar` varchar(255) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO `personagem` VALUES 
(1,'Albedo','Personagem','Principe do Giz', 'Raridade: 5 Estrelas, Arma: Espada, Visão:Geo, Sexo: Masculino, Aniversário: 13 de Setembro, Constelação:Princeps Cretaceus, Nação: Mondstadt, Afiliação: Cavaleiros de Favonius, Prato Especial: Sonho da Floresta, Como Obter: Evento de oração - Notícias Enigmáticas, Data de lançamento, 23 de dezembro de 2020; há 21 meses','albedo.png','https://static.wikia.nocookie.net/gensin-impact/images/0/00/Character_Albedo_Thumb.png/revision/latest?cb=20210213163457'),
(2,'Kamisato Ayaka','Personagem','Garça da Geada','Raridade: 5 Estrelas, Arma: Espada, Visão:Cryo, Nome Completo: Kamisato Ayaka, Sexo: Feminino, Aniversário: 28 de Setembro, Constelação: Guindaste de Neve, Nação: nazuma, Afiliação: Clã Kamisato Comissão Yashiro, Como Obter: Evento de Oração Jardim da Garça, Data de lançamento: 21 de julho de 2021; há 14 meses','ayaka.png', 'https://static.wikia.nocookie.net/genshin-impact/images/f/fd/Character_Kamisato_Ayaka_Thumb.png/revision/latest?cb=20210812051527&path-prefix=id'),
(3,'Diluc','Personagem','Herdeiro do Adega do Alvorecer','Raridade: 5 Estrelas, Arma: Espadão, Visão:Pyro, Nome Completo:Diluc Ragnvindr, Sexo: Masculino, Aniversário: 30 de Abril, Constelação: Noctua, Nação: Mondstadt,Afiliação: Adega do Alvorecer Organização de inteligência sem nome Cavaleiro de Favonius, Prato Especial:"Era Uma Vez em Mondstadt", Como Obter: Orações Data de lançamento: 28 de setembro de 2020; há 2 anos','diluc.png','https://static.wikia.nocookie.net/gensin-impact/images/0/02/Character_Diluc_Thumb.png/revision/latest?cb%3D20210213163824'),
(4,'Eula','Personagem','Dança da Onda Cintilante','Raridade: 5 Estrelas, Arma: Espadão, Visão:Cryo, Nome Completo: Eula Lawrence, Sexo: Feminino, Aniversário: 25 de Outubro, Constelação: Aphros Delos, Nação: Mondstadt, Afiliação: Cavaleiros de Favonius Clã Lawrence, Prato Especial: Torta de Tempestade, Como Obter: Formação das Ondas, Data de lançamento:18 de maio de 2021; há 17 meses','eula.png','https://static.wikia.nocookie.net/gensin-impact/images/d/d3/Character_Eula_Thumb.png/revision/latest?cb%3D20210511040616'),
(5,'Ganyu','Personagem','Defensora Devota', 'Raridade: 5 Estrelas, Arma: Arco, Visão:Cryo, Sexo: Feminino, Aniversário: 2 de dezembro, Constelação: Sinae Unicornis, Nação: Liyue, Afiliação: Pavilhão Yuehai, Prato Especial: Paz Próspera, Como Obter: Evento de Oração - À Deriva no Porto, Data de lançamento: 12 de janeiro de 2021; há 21 meses','ganyu.png','https://static.wikia.nocookie.net/gensin-impact/images/0/0a/Character_Ganyu_Thumb.png/revision/latest?cb%3D20210213162851'),
(6,'Hutao','Personagem','Fragrância de Ameixa Descongelada', 'Raridade: 5 Estrelas, Arma: Lança, Visão:Pyro, Sexo: Feminino, Aniversário:15 de julho, Constelação: Papilio Charontis, Nação: Liyue, Afiliação: Funerária Wangsheng - Família Hu, Prato Especial: Marcha Fantasmagórica, Como Obter: Evento de Oração - Momento de Florescer, Data de lançamento: 02 de março de 2021; há 19 meses','hutao.png', 'https://static.wikia.nocookie.net/gensin-impact/images/a/a4/Character_Hu_Tao_Thumb.png/revision/latest?cb%3D20210228210611'),
(7,'Jean','Personagem','Cavaleira de Dandelion','Raridade: 5 Estrelas, Arma: Espada, Visão:Anemo, Nome Completo: Jean Gunnhildr, Sexo: Feminino, Aniversário: 14 de Março, Constelação: Leo Minor, Nação: Mondstadt, Afiliação: Cavaleiros de Favonius - Quatro Ventos - Clã Gunnhildr, Prato Especial: Pizza Revigorante, Como Obter: Orações, Data de lançamento: 28 de setembro de 2020; há 2 anos','jean.png', 'https://static.wikia.nocookie.net/gensin-impact/images/8/89/Character_Jean_Thumb.png/revision/latest?cb%3D20220602180528'),
(8,'Keqing','Personagem','Trovão Condutor', 'Raridade: 5 Estrelas, Arma: Espada, Visão:Electro, Sexo:Feminino, Aniversário: 20 de Novembro, Constelação: Trulla Cementarii, Nação: Liyue, Afiliação: Qixing de Liyue, Prato Especial: Peixe Grelhado de Sobrevivência, Como Obter: Orações -- Evento de Oração - Dança de Lanternas, Data de lançamento: 28 de setembro de 2020; há 2 anos','keqing.png','https://static.wikia.nocookie.net/gensin-impact/images/0/06/Character_Keqing_Thumb.png/revision/latest?cb%3D20210213162751'),
(9,'Klee','Personagem','Sol Fugitivo','Raridade: 5 Estrelas, Arma: Catalisador, Visão:Pyro, Sexo: Feminino, Aniversário: 27 de Julho, Constelação: Trifolium, Nação: Mondstadt, Afiliação: Cavaleiros de Favonius, Prato Especial: Torrada de Peixe, Como Obter: Evento de Oração - Passos Flamejantes , Data de lançamento: 20 de outubro de 2020; há 24 meses','klee.png','https://static.wikia.nocookie.net/gensin-impact/images/c/c3/Character_Klee_Thumb.png/revision/latest?cb%3D20210214011911'),
(10,'Mona','Personagem','Reflexão Astral', 'Raridade: 5 Estrelas, Arma: Catalisador, Visão:Hydro, Nome Completo: Mona Megistus, Sexo: Feminino, Aniversário: 31 de Agosto, Constelação: Astrolabos, Nação: Mondstadt, Afiliação: Sociedade das Feiticeiras - Pássaro a Vapor - Prato Especial - Sabedoria Suprema (Vida), Como Obter: Orações, Data de lançamento: 28 de setembro de 2020; há 2 anos','mona.png','https://static.wikia.nocookie.net/gensin-impact/images/a/a0/Character_Mona_Thumb.png/revision/latest?cb%3D20220601033558'),
(11,'Qiqi','Personagem','Ressurreição Gélida','Raridade: 5 Estrelas, Arma: Espada, Visão:Cryo, Sexo: Feminino, Aniversário: 3 de Março, Constelação: Pristina Nola, Nação: Liyue, Afiliação: Chalé de Bubu, Prato Especial: Sem Futuro, Como Obter: Orações, Data de lançamento: 28 de setembro de 2020; há 2 anos','qiqi.png','https://static.wikia.nocookie.net/gensin-impact/images/d/d5/Character_Qiqi_Thumb.png/revision/latest?cb%3D20220316020612'),
(12,'Tartaglia','Personagem','Childe','Raridade: 5 Estrelas, Arma: Arco, Visão:Hydro, Nome Completo: Ajax, Sexo:Masculino, Aniversário: 20 de julho, Constelação: Monoceros Caeli, Nação: Snezhnaya, Afiliação: Fatui - Onze Mensageiros dos Fatui, Prato Especial: Pesca Extrema ,Como Obter: Evento de Oração - Despedida para o Norte, Data de lançamento: 11 de novembro de 2020; há 23 meses','tartaglia.png','https://static.wikia.nocookie.net/gensin-impact/images/5/53/Character_Tartaglia_Thumb.png/revision/latest?cb%3D20210213163935'),
(13,'Venti','Personagem','Cantor dos Ventos Celestiais','Raridade: 5 Estrelas, Arma: Arco, Visão:Anemo, Sexo: Masculino, Aniversário:16 de Junho, Constelação: Carmen Dei, Nação: Mondstadt, Afiliação: Cidade de Mondstadt - Arcontes, Prato Especial: Ratatouille Verdadeiro de Barbatos, Como Obter: Evento de Orações - Poemas em Taças, Data de lançamento: 28 de setembro de 2020; há 2 anos','venti.png','https://static.wikia.nocookie.net/gensin-impact/images/8/8d/Character_Venti_Thumb.png/revision/latest?cb%3D20210214011949'),
(14,'Xiao','Personagem','Guardião Yaksha','Raridade: 5 Estrelas, Arma: Lança, Visão:Anemo, Sexo: Masculino, Aniversário: 17 de Abril, Constelação: Alatus Nemeseos, Nação: Liyue, Afiliação: Adepti, Prato Especial: Sonhos Doces, Como Obter: Evento de Orações - Convite de Chamas, Data de lançamento: 03 de fevereiro de 2021; há 20 meses','xiao.png','https://static.wikia.nocookie.net/gensin-impact/images/b/b9/Character_Xiao_Thumb.png/revision/latest?cb%3D20210214012045'),
(15,'Yoimiya','Personagem','Chamas Brincando', 'Raridade: 5 Estrelas, Arma: Arco, Visão:Pyro, Nome Completo: Naganohara Yoimiya, Sexo: Feminino, Aniversário: 21 de Junho, Constelação: Carassius Auratus, Nação: Inazuma, Afiliação: Fogos de Artifício Naganohara, Prato Especial: Peixe do Festival de Verão, Como Obter: Evento de Oração - Chama da Via Láctea, Data de lançamento: 10 de agosto de 2021; há 14 meses','yoimiya.png', 'https://static.wikia.nocookie.net/gensin-impact/images/0/05/Character_Yoimiya_Thumb.png/revision/latest?cb%3D20220214235604'),
(16,'Zhongli','Personagem','Andarilho do Reino Mortal','Raridade: 5 Estrelas, Arma: Lança, Visão:Geo, Sexo: Masculino, Aniversário: 31 de Dezembro, Constelação: Lapis Dei, Nação: Liyue, Afiliação: Porto de Liyue - Funerária Wangsheng - Arcontes, Prato Especial: Sopa de Bambu Cozinhada Lentamente, Como Obter: Evento de Oração - Aristocracia Ermida, Data de lançamento: 01 de dezembro de 2020; há 22 meses','zhongli.png','https://static.wikia.nocookie.net/gensin-impact/images/c/c2/Character_Zhongli_Thumb.png/revision/latest?cb%3D20210213163026');
