version: '3'
services:
  feeds:
    image: genshin
    build: ./dockerfiles/servicos/
    hostname: feeds
    expose:
      - '5000'
    volumes:
      - './feeds:/servico'
    command: python3 servico.py
    networks:
      marcasnet:
        ipv4_address: 172.29.1.1
  bancodados:
    image: mysql
    hostname: bancodados
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      marcasnet:
        ipv4_address: 172.29.1.2
  arquivos:
    image: arquivos
    build: ./dockerfiles/nginx
    volumes:
      - './imagens:/usr/share/nginx/html'
    hostname: arquivos
    expose:
      - '80'
    networks:
      marcasnet:
        ipv4_address: 172.29.1.3    
networks:
  marcasnet:
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/16
